config/routes.rb
Rails.application.routes.draw do

  root to: "homes#index"
  resource  :users, only:[:new, :create]

  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"

  resources :questions do
    resources :question_similars, only:[:new, :create, :destroy]
    collection do
      get 'search'
    end
  end

  resources :tests, only:[:new, :create, :update] do
    collection do
      get 'rank'
    end
  end 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :question_similars, dependent: :destroy
  accepts_nested_attributes_for :question_similars, allow_destroy: true
  
  validates :question, presence: true

  def self.search(search)
    if search
      Question.where('question LIKE(?)', "%#{search}%")
    else
      Question.all
    end
  end
  
end

app/models/question_similar.rb
class QuestionSimilar < ApplicationRecord
  belongs_to :question
  validates :similar_word, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_secure_password
  validates :password_confirmation, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end


  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    @question = Question.count
  end

end

app/controllers/question_similars_controller.rb
class QuestionSimilarsController < ApplicationController
  def new
    @similar = QuestionSimilar.new
  end

  def create
    @similar = QuestionSimilar.new(params_question_similar)

    if @similar.save
      redirect_to edit_question_path(@similar.question)
    else
      render :new
    end
  end

  def destroy
    question = QuestionSimilar.find(params[:id])
    question.destroy
    redirect_to root_path
  end


  private

  def params_question_similar
    params.require(:question_similar).permit(:similar_word).merge(question_id: params[:question_id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only:[:edit, :update, :destroy, :show]

  def index
    @questions = Question.all.includes(:question_similars)
  end

  def new
    @question = Question.new
    @question.question_similars.build
  end

  def create
    @question = Question.new(params_question)

    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_path, notice: '単語を登録しました' }
        format.json { render :index, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def update

    respond_to do |format|
      if @question.update(params_question)
        format.html { redirect_to questions_path, notice: '更新しました' }
        format.json { render :index, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end

  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  def search
    @questions = Question.search(params[:search])
  end


  private

  def params_question
    params.require(:question).permit(:question, :description, question_similars_attributes: [:id, :similar_word, :_destroy])
  end

  def set_question
    @question = Question.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now[:alert] = 'ユーザー名又はパスワードが違います'
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to login_path notice: 'ログアウトしました'
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def new
    # 問題の変数
    session[:array] = []
    @questions = Question.all.sample(100)
    @description = [@questions[0],@questions[1],@questions[2]]
    @question = @description[1]
    
    if @questions.count < 5
      flash.now[:alert] = '単語を5つ以上登録してください'
      render template: "homes/index"
    end
    
    # sessionの初期変数
    session[:correct_answer] = 0
    session[:incorrect_answer] = 0
    session[:answer_check] = ''
    session[:answer_num] = 1
    
  end

  def create


    if (params[:question]).nil?
      params_question = 3
    else
      params_question = (params[:question]).delete("{:value=>}").to_i
    end

    # 問題のIDと解答のID(params)
    params_correct = (params[:correct_question]).delete("{:value=>}").to_i

    # session配列にIDの番号を入れる
    session[:array] << params_correct

    # 一度出たIDを出なくする
    @questions = Question.where.not(id: session[:array])
    
    
    if @questions.count > 0
      # 一度出たID以外のIDを１つ取得 ( 問題 )
      @question = @questions.sample()

      # 上のID以外の２つを取得
      description = Question.where.not(id: @question.id)
      descriptions = description.sample(2)
      
      # ３択のIDを取得 ( 解答 )
      @description = descriptions << @question
    end


    # 問題ページを遷移することに+1
    session[:answer_num] +=1


    if session[:answer_num] < 6

      # 答え合わせの条件分岐
      if params_question == params_correct
        session[:answer_check] = '正解'
        session[:correct_answer] +=1
      else
        session[:answer_check] = '不正解'
        session[:incorrect_answer] +=1
      end

    else
      # 答え合わせの条件分岐
      if params_question == params_correct
        session[:answer_check] = '正解'
        session[:correct_answer] +=1
      else
        session[:answer_check] = '不正解'
        session[:incorrect_answer] +=1
      end

      # 正答率
      session[:answer_rate] = session[:correct_answer] * 100 / 5
      rate = session[:answer_rate]
      highest = current_user.highest_rate


      # ハイスコア更新
      if highest.nil? or highest < rate  
        current_user.update_attribute(:highest_rate, rate)
      end

      redirect_to rank_tests_path
    end
  end



  def rank

    @rank = User.order(highest_rate: "DESC")
  
    only_ranks = @rank.map(&:highest_rate)

    
    if session[:correct_answer].present? && session[:answer_rate].present?


      #ハイスコアのみ取得
      only_ranks = (only_ranks << session[:answer_rate]).sort.reverse
      @current_rank = only_ranks.index(session[:answer_rate]) + 1

      # フラッシュメッセージ
      flash.now[:notice] = "お疲れ様でした!
      あなたの成績は、5問中#{session[:correct_answer]}問正解！！
      正解率#{session[:answer_rate]}%で、あなたの順位は#{@current_rank}位です"

    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :hight_rate)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/question_similars_helper.rb
module QuestionSimilarsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<h2>Main Menu</h2>
<p>下記のメニューよりクリックしてください。</p>


<%= link_to '単語帳', new_test_path %><br>
<%= link_to 'ランキング', rank_tests_path %><br>
<%= link_to '単語帳マスタメンテナンス', questions_path %><br>
<% if current_user %>
  <%= link_to 'ログアウト', logout_path, method: :delete%><br>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WORDBOOK</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container"> 
    <% flash.each do |message_type, message| %>
      <div class="alert alert-warning"<%= message_type %>>
        <%= message %>
      </div>
    <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/question_similars/new.html.erb
<h3>類義語追加</h3>

<%= form_with model: @similar, url: question_question_similars_path, local: true do |f| %>

<div class="form-group">
  <div class="similar_add">
    <%= f.label :類義語登録 %><br>
    <%= f.text_field :similar_word, class:"form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.submit "類義語登録", class:"btn btn-primary"%>
</div>

<% end %>

<div class="form-group">
  <%= link_to "戻る", questions_path %>
</div>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :question, '単語' %>
    <%= f.text_field :question, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description, '単語の説明' %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="question_similar_form">
    <%= f.label :similar_word, '類義語' %>
    <%= f.fields_for :question_similars do |f| %>
      <%= render 'question_similar_fields', f: f %>      
    <% end %>
    <div class="links">
      <p><%= link_to_add_association "＋追加", f, :question_similars, class:"add-to" %></p>
    </div>
  </div>

  <div>
    <%= f.submit '作成', class: 'btn btn-primary' %>
  </div>

<% end %>

<div>
  <%= link_to "戻る", questions_path%>
</div>

app/views/questions/_index.html.erb
<div class="form-group">
  <%= form_with url: search_questions_path, method: :get, local: true do |f| %>
    <%= f.text_field :search, placeholder: "検索" %>
    <%= f.submit'Search' %>
  <% end %>
</div>

<div class="form-group">
  <%= link_to '＋新規単語', new_question_path, class:"new-add"%>
</div>

<table class="table">
  <tr>
    <th scope="col">登録単語</th>
    <th scope="col">単語の説明</th>
    <th scope="col">修正</th>
    <th scope="col">削除</th>
  </tr>
  <% @questions.each do |question| %>
  <tr>
      <th scope="row"><%= link_to "#{question.question}", question_path(question.id) %></th>
      <td><%= link_to "#{question.description}", question_path(question.id) %></td>
      <td><%= link_to "修正する", edit_question_path(question.id) %></td>
      <td><%= link_to "削除する", "/questions/#{question.id}", method: :delete %></td>
  </tr>
  <% end %>
</table>

app/views/questions/_question_similar_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= f.text_field :similar_word, class: "form-control" %>
    <%= link_to_remove_association '削除', f, class:"similar-add"%>
  </div>
</div>

app/views/questions/edit.html.erb
<%= render 'layouts/error_messages', model: @question %>
<h3>単語修正</h3>
<%= render 'form', question: @question %>

app/views/questions/index.html.erb
<h1>単語マスタメンテナンス</h1>
<%= render('index') %>
<div><%= link_to 'メニューに戻る', root_path %></div>

app/views/questions/new.html.erb
<%= render 'layouts/error_messages', model: @question %>
<h3>単語帳新規作成</h3>
<%= render 'form', question: @question %>

app/views/questions/search.html.erb
<h1><%= "”#{(params[:search])}”" %>の検索結果</h1>

<% if @questions.present?%>
  <%= render('index') %>
<% else %>
  <h5>検索結果がありません</h5>
<% end %>


<div><%= link_to "戻る", questions_path %></div>

app/views/questions/show.html.erb
<h1>単語の詳細</h1>
<table class="table">
  <tr>
    <th scope="col">登録単語</th>
    <th scope="col">単語の説明</th>
    <th scope="col">類義語</th>
    <th scope="col">修正</th>
    <th scope="col">削除</th>
  </tr>
  <tr>
    <th scope="row"><%= @question.question %></th>
    <td><%= @question.description %></td>

    <td>
      <% @question.question_similars.each do |similar|%>
        <%= similar.similar_word %><br>
      <% end %>
    </td>
    <td><%= link_to "修正する", edit_question_path(@question.id) %></td>
    <td><%= link_to "削除する",  "/questions/#{@question.id}", method: :delete %></td>
</table>



<div class="form-group">
  <%= link_to "戻る", questions_path %>
</div>

app/views/users/new.html.erb
<%= render 'layouts/error_messages', model: @user %>

<h3>ユーザー作成画面</h3>
<%= form_with model: @user, local: true do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "新規作成", class:"btn btn-primary"%>
  </div>

  <div class="form-group">
  <%= link_to "ログインページ", login_path %>
  <div>

<% end %>